/*
    id: 
    image:
    userName:
    lastMessage:
    lastMessageTime:
    unreadMessageCount:
    isMuted:
    isGroup:
    groupName:
    userJoined:
    newUserName:
*/

const Data = [
    {
        id: 1,
        image: require('../assets/SGCodes.jpg'),
        userName: 'John',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute.',
        userJoined: true,
        newUserName: "S.G.",
        lastMessageTime: '1:00 PM',
        unreadMessageCount: 0,
        groupName: "S.G.Codes",
        isGroup: true,
    },
    {
        id: 2,
        image: require('../assets/user2.jpg'),
        userName: 'Kirti',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute.',
        newUserName: 'Amit',
        lastMessageTime: 'Mon',
        unreadMessageCount: 10,
        groupName: 'Creators',
        isGroup: true,
    },
    {
        id: 3,
        image: require('../assets/user3.jpg'),
        userName: 'Aashish',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute.',
        userJoined: false,
        isMuted: true,
        lastMessageTime: '7:06 AM',
        unreadMessageCount: 1065,
        isGroup: false,
    },
    {
        id: 4,
        image: require('../assets/user4.jpg'),
        userName: 'Vijay',
        lastMessage: 'Reprehenderit dolore non dolor anim non voluptate voluptate cillum velit et veniam dolor. Elit magna amet reprehenderit nulla est deserunt. Anim labore ea in esse labore dolore eu laborum labore fugiat ad occaecat. Nulla tempor elit consequat labore ex incididunt elit incididunt fugiat aliqua consectetur pariatur tempor aliquip.',
        userJoined: false,
        isMuted: true,
        lastMessageTime: '5:02 PM',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 5,
        image: require('../assets/NodeJs.png'),
        userName: 'Martha',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute.',
        userJoined: false,
        newUserName: "Kishan",
        lastMessageTime: '10:00 PM',
        unreadMessageCount: 0,
        groupName: 'Node & React Learners',
        isGroup: true,
    },
    {
        id: 6,
        image: require('../assets/Jobs.png'),
        userName: 'Chris',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute.',
        userJoined: true,
        newUserName: "Anand",
        groupName: "Job Notify",
        lastMessageTime: '4:37 PM',
        unreadMessageCount: 100,
        isGroup: true,
    },
    {
        id: 7,
        image: require('../assets/user7.jpg'),
        userName: 'Simran',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute.',
        userJoined: false,
        lastMessageTime: '9:58 PM',
        unreadMessageCount: 8,
        isGroup: false,
    },
    {
        id: 8,
        image: require('../assets/user8.jpg'),
        userName: 'Jessica',
        lastMessage: 'Consectetur non irure duis sunt proident mollit nostrud do. Laboris fugiat labore esse deserunt proident incididunt deserunt laborum.',
        userJoined: false,
        lastMessageTime: '1:05 AM',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 9,
        image: require('../assets/Android.png'),
        userName: 'John',
        isMuted: true,
        lastMessage: 'Aute ut Proident proident cillum incididunt dolor laborum magna do adipisicing nulla magna minim qui.',
        userJoined: false,
        lastMessageTime: 'Thur',
        unreadMessageCount: 1,
        groupName: "Android Champions",
        isGroup: true,
    },
    {
        id: 10,
        image: require('../assets/user10.jpg'),
        userName: 'Clarence',
        isMuted: false,
        lastMessage: 'Ut ad veniam sint ea exercitation est. Ad duis fugiat in mollit pariatur id ea adipisicing proident. Veniam anim sint irure nostrud labore. Amet ut do laborum amet incididunt occaecat voluptate magna.',
        userJoined: false,
        lastMessageTime: '6:30 PM',
        unreadMessageCount: 19,
        isGroup: false,
    },
    {
        id: 11,
        image: require('../assets/user11.jpg'),
        userName: 'Edward',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute. Enim labore commodo tempor quis officia aute.',
        userJoined: false,
        lastMessageTime: '10:05 AM',
        unreadMessageCount: 25,
        isGroup: false,
    },
    {
        id: 12,
        image: require('../assets/Friends.jpg'),
        newUserName: 'Jesse',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute.',
        userJoined: true,
        lastMessageTime: 'Now',
        unreadMessageCount: 5,
        isGroup: true,
        groupName: "Friends",
        isMuted: true
    },
    {
        id: 13,
        image: require('../assets/user13.jpg'),
        userName: 'Peter',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute. Fugiat ut exercitation consequat nostrud voluptate ullamco consequat incididunt labore.',
        userJoined: false,
        lastMessageTime: '4:30 PM',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 14,
        image: require('../assets/user14.jpg'),
        userName: 'Julius',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute. Ipsum id sint officia fugiat labore aliquip voluptate irure exercitation sint fugiat duis est voluptate.',
        userJoined: false,
        lastMessageTime: 'Wed',
        unreadMessageCount: 10,
        isGroup: false,
    },
    {
        id: 15,
        image: require('../assets/user15.jpg'),
        userName: 'Roosie',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute. Proident excepteur exercitation veniam commodo et labore cupidatat laboris.',
        userJoined: false,
        lastMessageTime: '1:00 PM',
        unreadMessageCount: 22,
        isGroup: false,
    },
    {
        id: 16,
        image: require('../assets/user16.jpg'),
        userName: 'Alex',
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute. Id consectetur duis minim duis excepteur pariatur Lorem id aliquip velit.',
        userJoined: false,
        lastMessageTime: 'Mon',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 17,
        image: require('../assets/user17.jpg'),
        userName: 'Issac',
        isMuted: true,
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute. Occaecat commodo amet pariatur qui incididunt duis et dolor.',
        userJoined: false,
        lastMessageTime: '7:10 PM',
        unreadMessageCount: 5,
        isGroup: false,
    }, 
    {
        id: 18,
        image: require('../assets/user18.jpg'),
        userName: 'Sarthak',
        isMuted: false,
        lastMessage: 'Dolor excepteur dolor magna do nulla laboris aute. Occaecat commodo amet pariatur qui incididunt duis et dolor.',
        userJoined: false,
        lastMessageTime: '7:10 PM',
        unreadMessageCount: 508,
        isGroup: true,
        groupName: "Rockers"
    }, 
    {
        id: 19,
        image: require('../assets/user19.jpg'),
        userName: 'Emma',
        isMuted: false,
        lastMessage: 'Lorem tempor Lorem commodo fugiat ex tempor laboris fugiat laboris sit labore incididunt culpa sunt.. Aliquip tempor sit irure sint dolore aute..',
        userJoined: false,
        lastMessageTime: '11:34 PM',
        unreadMessageCount: 12,
        isGroup: false,
    }, 
    {
        id: 20,
        image: require('../assets/user20.jpg'),
        userName: 'Ronald',
        isMuted: true,
        lastMessage: 'Excepteur duis sunt est pariatur eiusmod amet. Reprehenderit quis incididunt qui nulla mollit. Velit incididunt sunt commodo enim id ullamco mollit commodo minim excepteur id nisi ullamco.',
        userJoined: false,
        lastMessageTime: '9:49 AM',
        unreadMessageCount: 36,
        isGroup: false,
    },
    {
        id: 21,
        image: require('../assets/user21.jpg'),
        userName: 'Sophia',
        isMuted: false,
        lastMessage: 'Commodo ea aute et adipisicing eu incididunt esse nostrud commodo aliqua. Minim et non nisi id velit nostrud dolor incididunt velit proident sint occaecat velit aute.',
        userJoined: false,
        lastMessageTime: 'Fri',
        unreadMessageCount: 0,
        isGroup: false,
    },
    {
        id: 22,
        image: require('../assets/SonyMusic.png'),
        isMuted: true,
        lastMessage: 'Esse sunt ullamco ipsum laboris esse aliqua quis eu cillum duis velit. Elit deserunt enim fugiat in consequat enim do laboris.',
        userJoined: true,
        newUserName: "Mia",
        lastMessageTime: 'Now',
        unreadMessageCount: 0,
        isGroup: true,
        groupName: "Sony Music"
    }, 
]

export default Data;